using Terraria.ModLoader;
namespace StarfallThrone.Content.Ecology.Combat;

[AutoloadBossHead] public sealed class EcologyBoss0 : EcologyBossNPC { public override int Index => 0; }
public sealed class EcologySummon0 : EcologySummonBase { public override int Index => 0; }
[AutoloadBossHead] public sealed class EcologyBoss1 : EcologyBossNPC { public override int Index => 1; }
public sealed class EcologySummon1 : EcologySummonBase { public override int Index => 1; }
[AutoloadBossHead] public sealed class EcologyBoss2 : EcologyBossNPC { public override int Index => 2; }
public sealed class EcologySummon2 : EcologySummonBase { public override int Index => 2; }
[AutoloadBossHead] public sealed class EcologyBoss3 : EcologyBossNPC { public override int Index => 3; }
public sealed class EcologySummon3 : EcologySummonBase { public override int Index => 3; }
[AutoloadBossHead] public sealed class EcologyBoss4 : EcologyBossNPC { public override int Index => 4; }
public sealed class EcologySummon4 : EcologySummonBase { public override int Index => 4; }
[AutoloadBossHead] public sealed class EcologyBoss5 : EcologyBossNPC { public override int Index => 5; }
public sealed class EcologySummon5 : EcologySummonBase { public override int Index => 5; }
[AutoloadBossHead] public sealed class EcologyBoss6 : EcologyBossNPC { public override int Index => 6; }
public sealed class EcologySummon6 : EcologySummonBase { public override int Index => 6; }
[AutoloadBossHead] public sealed class EcologyBoss7 : EcologyBossNPC { public override int Index => 7; }
public sealed class EcologySummon7 : EcologySummonBase { public override int Index => 7; }
[AutoloadBossHead] public sealed class EcologyBoss8 : EcologyBossNPC { public override int Index => 8; }
public sealed class EcologySummon8 : EcologySummonBase { public override int Index => 8; }
[AutoloadBossHead] public sealed class EcologyBoss9 : EcologyBossNPC { public override int Index => 9; }
public sealed class EcologySummon9 : EcologySummonBase { public override int Index => 9; }
public sealed class EcologyMob0 : EcologyMobNPC { public override int Index => 0; }
public sealed class EcologyMob1 : EcologyMobNPC { public override int Index => 1; }
public sealed class EcologyMob2 : EcologyMobNPC { public override int Index => 2; }
public sealed class EcologyMob3 : EcologyMobNPC { public override int Index => 3; }
public sealed class EcologyMob4 : EcologyMobNPC { public override int Index => 4; }
public sealed class EcologyMob5 : EcologyMobNPC { public override int Index => 5; }
public sealed class EcologyMob6 : EcologyMobNPC { public override int Index => 6; }
public sealed class EcologyMob7 : EcologyMobNPC { public override int Index => 7; }
public sealed class EcologyMob8 : EcologyMobNPC { public override int Index => 8; }
public sealed class EcologyMob9 : EcologyMobNPC { public override int Index => 9; }
public sealed class EcologyMob10 : EcologyMobNPC { public override int Index => 10; }
public sealed class EcologyMob11 : EcologyMobNPC { public override int Index => 11; }
public sealed class EcologyMob12 : EcologyMobNPC { public override int Index => 12; }
public sealed class EcologyMob13 : EcologyMobNPC { public override int Index => 13; }
public sealed class EcologyMob14 : EcologyMobNPC { public override int Index => 14; }
public sealed class EcologyMob15 : EcologyMobNPC { public override int Index => 15; }
public sealed class EcologyMob16 : EcologyMobNPC { public override int Index => 16; }
public sealed class EcologyMob17 : EcologyMobNPC { public override int Index => 17; }
public sealed class EcologyMob18 : EcologyMobNPC { public override int Index => 18; }
public sealed class EcologyMob19 : EcologyMobNPC { public override int Index => 19; }
public sealed class EcologyMob20 : EcologyMobNPC { public override int Index => 20; }
public sealed class EcologyMob21 : EcologyMobNPC { public override int Index => 21; }
public sealed class EcologyMob22 : EcologyMobNPC { public override int Index => 22; }
public sealed class EcologyMob23 : EcologyMobNPC { public override int Index => 23; }
public sealed class EcologyMob24 : EcologyMobNPC { public override int Index => 24; }
public sealed class EcologyMob25 : EcologyMobNPC { public override int Index => 25; }
public sealed class EcologyMob26 : EcologyMobNPC { public override int Index => 26; }
public sealed class EcologyMob27 : EcologyMobNPC { public override int Index => 27; }
public sealed class EcologyMob28 : EcologyMobNPC { public override int Index => 28; }
public sealed class EcologyMob29 : EcologyMobNPC { public override int Index => 29; }
public sealed class EcologyMob30 : EcologyMobNPC { public override int Index => 30; }
public sealed class EcologyMob31 : EcologyMobNPC { public override int Index => 31; }
public sealed class EcologyMob32 : EcologyMobNPC { public override int Index => 32; }
public sealed class EcologyMob33 : EcologyMobNPC { public override int Index => 33; }
public sealed class EcologyMob34 : EcologyMobNPC { public override int Index => 34; }
public sealed class EcologyMob35 : EcologyMobNPC { public override int Index => 35; }
public sealed class EcologyMob36 : EcologyMobNPC { public override int Index => 36; }
public sealed class EcologyMob37 : EcologyMobNPC { public override int Index => 37; }
public sealed class EcologyMob38 : EcologyMobNPC { public override int Index => 38; }
public sealed class EcologyMob39 : EcologyMobNPC { public override int Index => 39; }

