using Terraria.ModLoader;
namespace StarfallThrone.Content.Pantheon.Equipment;
public sealed class PantheonWeapon0:PantheonWeapon{public override int Index=>0;}
public sealed class PantheonWeapon1:PantheonWeapon{public override int Index=>1;}
public sealed class PantheonWeapon2:PantheonWeapon{public override int Index=>2;}
public sealed class PantheonWeapon3:PantheonWeapon{public override int Index=>3;}
public sealed class PantheonWeapon4:PantheonWeapon{public override int Index=>4;}
public sealed class PantheonWeapon5:PantheonWeapon{public override int Index=>5;}
public sealed class PantheonWeapon6:PantheonWeapon{public override int Index=>6;}
public sealed class PantheonWeapon7:PantheonWeapon{public override int Index=>7;}
public sealed class PantheonWeapon8:PantheonWeapon{public override int Index=>8;}
public sealed class PantheonWeapon9:PantheonWeapon{public override int Index=>9;}
public sealed class PantheonWeapon10:PantheonWeapon{public override int Index=>10;}
public sealed class PantheonWeapon11:PantheonWeapon{public override int Index=>11;}
public sealed class PantheonWeapon12:PantheonWeapon{public override int Index=>12;}
public sealed class PantheonWeapon13:PantheonWeapon{public override int Index=>13;}
public sealed class PantheonWeapon14:PantheonWeapon{public override int Index=>14;}
public sealed class PantheonWeapon15:PantheonWeapon{public override int Index=>15;}
public sealed class PantheonWeapon16:PantheonWeapon{public override int Index=>16;}
public sealed class PantheonWeapon17:PantheonWeapon{public override int Index=>17;}
public sealed class PantheonWeapon18:PantheonWeapon{public override int Index=>18;}
public sealed class PantheonWeapon19:PantheonWeapon{public override int Index=>19;}
public sealed class PantheonWeapon20:PantheonWeapon{public override int Index=>20;}
public sealed class PantheonWeapon21:PantheonWeapon{public override int Index=>21;}
public sealed class PantheonWeapon22:PantheonWeapon{public override int Index=>22;}
public sealed class PantheonWeapon23:PantheonWeapon{public override int Index=>23;}
public sealed class PantheonWeapon24:PantheonWeapon{public override int Index=>24;}
public sealed class PantheonWeapon25:PantheonWeapon{public override int Index=>25;}
public sealed class PantheonWeapon26:PantheonWeapon{public override int Index=>26;}
public sealed class PantheonWeapon27:PantheonWeapon{public override int Index=>27;}
public sealed class PantheonWeapon28:PantheonWeapon{public override int Index=>28;}
public sealed class PantheonWeapon29:PantheonWeapon{public override int Index=>29;}
public sealed class PantheonWeapon30:PantheonWeapon{public override int Index=>30;}
public sealed class PantheonWeapon31:PantheonWeapon{public override int Index=>31;}
public sealed class PantheonWeapon32:PantheonWeapon{public override int Index=>32;}
public sealed class PantheonWeapon33:PantheonWeapon{public override int Index=>33;}
public sealed class PantheonWeapon34:PantheonWeapon{public override int Index=>34;}
public sealed class PantheonWeapon35:PantheonWeapon{public override int Index=>35;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor0:PantheonArmor{public override int Index=>0;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor1:PantheonArmor{public override int Index=>1;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor2:PantheonArmor{public override int Index=>2;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor3:PantheonArmor{public override int Index=>3;}
[AutoloadEquip(EquipType.Body)] public sealed class PantheonArmor4:PantheonArmor{public override int Index=>4;}
[AutoloadEquip(EquipType.Legs)] public sealed class PantheonArmor5:PantheonArmor{public override int Index=>5;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor6:PantheonArmor{public override int Index=>6;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor7:PantheonArmor{public override int Index=>7;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor8:PantheonArmor{public override int Index=>8;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor9:PantheonArmor{public override int Index=>9;}
[AutoloadEquip(EquipType.Body)] public sealed class PantheonArmor10:PantheonArmor{public override int Index=>10;}
[AutoloadEquip(EquipType.Legs)] public sealed class PantheonArmor11:PantheonArmor{public override int Index=>11;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor12:PantheonArmor{public override int Index=>12;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor13:PantheonArmor{public override int Index=>13;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor14:PantheonArmor{public override int Index=>14;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor15:PantheonArmor{public override int Index=>15;}
[AutoloadEquip(EquipType.Body)] public sealed class PantheonArmor16:PantheonArmor{public override int Index=>16;}
[AutoloadEquip(EquipType.Legs)] public sealed class PantheonArmor17:PantheonArmor{public override int Index=>17;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor18:PantheonArmor{public override int Index=>18;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor19:PantheonArmor{public override int Index=>19;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor20:PantheonArmor{public override int Index=>20;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor21:PantheonArmor{public override int Index=>21;}
[AutoloadEquip(EquipType.Body)] public sealed class PantheonArmor22:PantheonArmor{public override int Index=>22;}
[AutoloadEquip(EquipType.Legs)] public sealed class PantheonArmor23:PantheonArmor{public override int Index=>23;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor24:PantheonArmor{public override int Index=>24;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor25:PantheonArmor{public override int Index=>25;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor26:PantheonArmor{public override int Index=>26;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor27:PantheonArmor{public override int Index=>27;}
[AutoloadEquip(EquipType.Body)] public sealed class PantheonArmor28:PantheonArmor{public override int Index=>28;}
[AutoloadEquip(EquipType.Legs)] public sealed class PantheonArmor29:PantheonArmor{public override int Index=>29;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor30:PantheonArmor{public override int Index=>30;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor31:PantheonArmor{public override int Index=>31;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor32:PantheonArmor{public override int Index=>32;}
[AutoloadEquip(EquipType.Head)] public sealed class PantheonArmor33:PantheonArmor{public override int Index=>33;}
[AutoloadEquip(EquipType.Body)] public sealed class PantheonArmor34:PantheonArmor{public override int Index=>34;}
[AutoloadEquip(EquipType.Legs)] public sealed class PantheonArmor35:PantheonArmor{public override int Index=>35;}
public sealed class PantheonExpert0:PantheonExpert{public override int Index=>0;}
public sealed class PantheonExpert1:PantheonExpert{public override int Index=>1;}
public sealed class PantheonExpert2:PantheonExpert{public override int Index=>2;}
public sealed class PantheonExpert3:PantheonExpert{public override int Index=>3;}
public sealed class PantheonExpert4:PantheonExpert{public override int Index=>4;}
public sealed class PantheonExpert5:PantheonExpert{public override int Index=>5;}
public sealed class PantheonExpert6:PantheonExpert{public override int Index=>6;}
public sealed class PantheonExpert7:PantheonExpert{public override int Index=>7;}
public sealed class PantheonExpert8:PantheonExpert{public override int Index=>8;}
public sealed class PantheonExpert9:PantheonExpert{public override int Index=>9;}
public sealed class PantheonExpert10:PantheonExpert{public override int Index=>10;}
public sealed class PantheonExpert11:PantheonExpert{public override int Index=>11;}
public sealed class PantheonExpert12:PantheonExpert{public override int Index=>12;}
public sealed class PantheonExpert13:PantheonExpert{public override int Index=>13;}
public sealed class PantheonExpert14:PantheonExpert{public override int Index=>14;}
public sealed class PantheonExpert15:PantheonExpert{public override int Index=>15;}
public sealed class PantheonExpert16:PantheonExpert{public override int Index=>16;}
public sealed class PantheonMinion1:PantheonMinion{public override int Boss=>1;}
public sealed class PantheonMinionBuff1:PantheonMinionBuff{public override int Boss=>1;}
public sealed class PantheonMinion3:PantheonMinion{public override int Boss=>3;}
public sealed class PantheonMinionBuff3:PantheonMinionBuff{public override int Boss=>3;}
public sealed class PantheonMinion5:PantheonMinion{public override int Boss=>5;}
public sealed class PantheonMinionBuff5:PantheonMinionBuff{public override int Boss=>5;}
public sealed class PantheonMinion7:PantheonMinion{public override int Boss=>7;}
public sealed class PantheonMinionBuff7:PantheonMinionBuff{public override int Boss=>7;}
public sealed class PantheonMinion9:PantheonMinion{public override int Boss=>9;}
public sealed class PantheonMinionBuff9:PantheonMinionBuff{public override int Boss=>9;}
public sealed class PantheonMinion11:PantheonMinion{public override int Boss=>11;}
public sealed class PantheonMinionBuff11:PantheonMinionBuff{public override int Boss=>11;}
public sealed class PantheonMinion13:PantheonMinion{public override int Boss=>13;}
public sealed class PantheonMinionBuff13:PantheonMinionBuff{public override int Boss=>13;}
public sealed class PantheonMinion15:PantheonMinion{public override int Boss=>15;}
public sealed class PantheonMinionBuff15:PantheonMinionBuff{public override int Boss=>15;}
public sealed class PantheonMinion16:PantheonMinion{public override int Boss=>16;}
public sealed class PantheonMinionBuff16:PantheonMinionBuff{public override int Boss=>16;}

